### ISSUE TITLE
Automated email list for next cohort (2023) fellowship applications?

### ISSUE THREAD

**Issue by officialfrancismendoza** [eth-protocol-fellows/cohort-three#249]
Hi. I found out about this fellowship program too late but am very interested in applying to the next cohort. Ran a search on the website but couldn't find any email list where I can subscribe for updates. Any way I could get automatically notified on information for next year's cohort? Thank you!

**Comment by taxmeifyoucan** [comment]
Hey! Yes there is a google group mailing list where we post all important updates about the program. Join here https://groups.google.com/a/ethereum.org/forum/#!forum/protocol-fellowship-group/join
