### ISSUE TITLE
Is it full time only?

### ISSUE THREAD

**Issue by Sohojoe** [eth-protocol-fellows/cohort-three#4]
Do candidates need to commit full time to the program? Or can we do it while keeping a day. Maybe another way to ask this is what is the expected time commitment per week?

Fanks!

**Comment by taxmeifyoucan** [comment]
From [FAQ](https://github.com/eth-protocol-fellows/cohort-three/blob/master/program-guide/faq.md):

- **I'm not able to commit to "full time" (aka 40 hours a week).  Can I still apply?**
    - Yes. There are no hard restrictions on how many hours you must put towards the program. The amount of time you will need to invest is going to depend on your current level of knowledge and what project you choose to pursue.  It will likely be difficult to be successful in the program if you are unable to commit at least 20 hours per week.


 In the application you can indicate how much time you can commit.
